const { PrismaClient } = require('@prisma/client');
require('dotenv').config();
const prisma = new PrismaClient();

async function main() {
  console.log("Start seeding ...");

  const products = [
    {
      id: 1,
      name: "Fjallraven - Fits 15 Laptops",
      price: 109.95,
      description: "Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday",
      category: "men's clothing",
      image: "https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_t.png",
      rating: 3.9,
      ratingCount: 120,
      inStock: true,
    },
    {
      id: 2,
      name: "Mens Casual T-Shirts",
      price: 22.3,
      description: "Slim-fitting style, contrast raglan long sleeve, three-button henley placket, light weight & soft fabric for breathable and comfortable wearing.",
      category: "men's clothing",
      image: "https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_t.png",
      rating: 4.1,
      ratingCount: 259,
      inStock: true,
    },
    {
      id: 3,
      name: "Mens Cotton Jacket",
      price: 55.99,
      description: "Great outerwear jackets for Spring/Autumn/Winter, suitable for many occasions, such as working, hiking, camping, mountain/rock climbing, cycling, traveling or other outdoors.",
      category: "men's clothing",
      image: "https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_t.png",
      rating: 4.7,
      ratingCount: 500,
      inStock: true,
    },
    {
      id: 4,
      name: "Mens Casual Slim Fit",
      price: 15.99,
      description: "The color could be slightly different between on the screen and in practice. Please note that body builds vary by person, therefore, detailed size information should be reviewed below.",
      category: "men's clothing",
      image: "https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_t.png",
      rating: 2.1,
      ratingCount: 430,
      inStock: true,
    },
    {
      id: 5,
      name: "Naga Gold & Silver Bracelet",
      price: 695,
      description: "From our Legends Collection, the Naga was inspired by the mythical water dragon that protects the ocean's pearl. Wear facing inward to be bestowed with love and abundance.",
      category: "jewelery",
      image: "https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_t.png",
      rating: 4.6,
      ratingCount: 400,
      inStock: true,
    },
    {
      id: 6,
      name: "Solid Gold Petite Micropave",
      price: 168,
      description: "Satisfaction Guaranteed. Return or exchange any order within 30 days. Designed and sold by Hafeez Center in the United States.",
      category: "jewelery",
      image: "https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_t.png",
      rating: 3.9,
      ratingCount: 70,
      inStock: true,
    },
    {
      id: 7,
      name: "White Gold Plated Princess",
      price: 9.99,
      description: "Classic Created Wedding Engagement Solitaire Diamond Promise Ring for Her. Gifts to spoil your love more for Engagement, Wedding, Anniversary, Valentine's Day.",
      category: "jewelery",
      image: "https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_t.png",
      rating: 3,
      ratingCount: 400,
      inStock: true,
    },
    {
      id: 8,
      name: "Pierced Owl Rose Gold",
      price: 10.99,
      description: "Rose Gold Plated Double Flared Tunnel Plug Earrings. Made of 316L Stainless Steel",
      category: "jewelery",
      image: "https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_t.png",
      rating: 1.9,
      ratingCount: 100,
      inStock: false,
    },
    {
      id: 9,
      name: "2TB External Hard Drive - USB 3.0",
      price: 64,
      description: "USB 3.0 and USB 2.0 Compatibility Fast data transfers Improve PC Performance High Capacity; Compatibility Formatted NTFS for Windows 10, Windows 8.1, Windows 7.",
      category: "electronics",
      image: "https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_t.png",
      rating: 3.3,
      ratingCount: 203,
      inStock: true,
    },
    {
      id: 10,
      name: "SanDisk SSD PLUS 1TB Internal SSD",
      price: 109,
      description: "Easy upgrade for faster boot up, shutdown, application load and response. Boosts burst write performance, making it ideal for typical PC workloads.",
      category: "electronics",
      image: "https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_t.png",
      rating: 2.9,
      ratingCount: 470,
      inStock: true,
    },
    {
      id: 11,
      name: "Silicon Power 256GB SSD",
      price: 109,
      description: "3D NAND flash are applied to deliver high transfer speeds. The advanced SLC Cache Technology allows performance boost and longer lifespan.",
      category: "electronics",
      image: "https://fakestoreapi.com/img/71kWymZ+c+L._AC_SX679_t.png",
      rating: 4.8,
      ratingCount: 319,
      inStock: true,
    },
    {
      id: 12,
      name: "WD 4TB Gaming Drive",
      price: 114,
      description: "Expand your PS4 gaming experience, Play anywhere Fast and easy, setup Sleek design with high capacity, 3-year manufacturer's limited warranty",
      category: "electronics",
      image: "https://fakestoreapi.com/img/61mtL65D4cL._AC_SX679_t.png",
      rating: 4.8,
      ratingCount: 400,
      inStock: true,
    },
    {
      id: 13,
      name: "Acer 21.5 inches Full HD",
      price: 599,
      description: "21.5 inches Full HD (1920 x 1080) widescreen IPS display And Radeon free Sync technology. Zero-frame design | ultra-thin | 4ms response time | IPS panel.",
      category: "electronics",
      image: "https://fakestoreapi.com/img/81QpkIctqPL._AC_SX679_t.png",
      rating: 2.9,
      ratingCount: 250,
      inStock: true,
    },
    {
      id: 14,
      name: "Samsung 49-Inch QLED",
      price: 999.99,
      description: "49 INCH SUPER ULTRAWIDE 32:9 CURVED GAMING MONITOR with dual 27 inch screen side by side. 144HZ HIGH REFRESH RATE and 1ms ultra fast response time.",
      category: "electronics",
      image: "https://fakestoreapi.com/img/81Zt42ioCgL._AC_SX679_t.png",
      rating: 2.2,
      ratingCount: 140,
      inStock: false,
    },
    {
      id: 15,
      name: "BIYLACLESEN Snowboard Jacket",
      price: 56.99,
      description: "Material: 100% Polyester; Detachable Liner Fabric: Warm Fleece. 3 in 1 Detachable Design provide more convenience, suitable for different season.",
      category: "women's clothing",
      image: "https://fakestoreapi.com/img/51Y5NI-I5jL._AC_UX679_t.png",
      rating: 2.6,
      ratingCount: 235,
      inStock: true,
    },
    {
      id: 16,
      name: "Faux Leather Moto Biker Jacket",
      price: 29.95,
      description: "100% POLYURETHANE shell, Faux leather material for style and comfort. 2-For-One Hooded denim style faux leather jacket.",
      category: "women's clothing",
      image: "https://fakestoreapi.com/img/81XH0e8fefL._AC_UY879_t.png",
      rating: 2.9,
      ratingCount: 340,
      inStock: true,
    },
    {
      id: 17,
      name: "Rain Jacket Women Raincoats",
      price: 39.99,
      description: "Lightweight perfect for trip or casual wear. Long sleeve with hooded, adjustable drawstring waist design. The Raincoat has 2 side pockets.",
      category: "women's clothing",
      image: "https://fakestoreapi.com/img/71HblAHs5xL._AC_UY879_-2t.png",
      rating: 3.8,
      ratingCount: 679,
      inStock: true,
    },
    {
      id: 18,
      name: "MBJ Women's Short Sleeve Boat Neck",
      price: 9.85,
      description: "95% RAYON 5% SPANDEX, Made in USA or Imported, Do Not Bleach, Lightweight fabric with great stretch for comfort.",
      category: "women's clothing",
      image: "https://fakestoreapi.com/img/71z3kpMAYsL._AC_UY879_t.png",
      rating: 4.7,
      ratingCount: 130,
      inStock: true,
    },
    {
      id: 19,
      name: "Opna Women's Short Sleeve",
      price: 7.95,
      description: "100% Polyester, Machine wash. Lightweight, roomy and highly breathable with moisture wicking fabric which helps to keep moisture away.",
      category: "women's clothing",
      image: "https://fakestoreapi.com/img/51eg55uWmdL._AC_UX679_t.png",
      rating: 4.5,
      ratingCount: 146,
      inStock: true,
    },
    {
      id: 20,
      name: "DANVOUY Womens T Shirt Casual Short",
      price: 12.99,
      description: "95%Cotton,5%Spandex, Features: Casual, Short Sleeve, Letter Print,V-Neck,Fashion Tees, The fabric is soft and has some stretch.",
      category: "women's clothing",
      image: "https://fakestoreapi.com/img/61pHAEJ4NML._AC_UX679_t.png",
      rating: 3.6,
      ratingCount: 145,
      inStock: true,
    },
  ];

  console.log("Seeding products...");
  for (const product of products) {
    await prisma.product.upsert({
      where: { id: product.id },
      update: {},
      create: product,
    });
  }

  console.log(`Seeded ${products.length} products successfully.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });